# Generated by Django 3.0.2 on 2020-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200123_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mileage',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
